#############################################
# Stage 1: Resolve Spark dependencies
#############################################

FROM apache/spark:4.2.0-scala2.13-java21-python3-ubuntu AS spark-deps

USER root

COPY spark-packages.txt /tmp/spark-packages.txt

RUN --mount=type=cache,target=/root/.ivy2.5.2 \
    echo "pass" > /tmp/noop.py && \
    /opt/spark/bin/spark-submit \
      --packages "$(paste -sd, /tmp/spark-packages.txt)" \
      /tmp/noop.py && \
    mkdir -p /spark-jars && \
    cp /root/.ivy2.5.2/jars/*.jar /spark-jars/


#############################################
# Stage 2: Build final Spark image
#############################################

FROM apache/spark:4.2.0-scala2.13-java21-python3-ubuntu

USER root


#############################################
# Python 3.13 installation
#############################################

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        software-properties-common \
        curl \
        ca-certificates && \
    add-apt-repository -y ppa:deadsnakes/ppa && \
    apt-get update && \
    apt-get install -y --no-install-recommends \
        python3.13 \
        python3.13-venv \
        python3.13-dev && \
    rm -rf /var/lib/apt/lists/*


#############################################
# Python dependency manager
#############################################

COPY --from=ghcr.io/astral-sh/uv:0.11.29 \
    /uv \
    /uvx \
    /usr/local/bin/


ENV UV_PROJECT_ENVIRONMENT=/opt/.spark-venv


#############################################
# Install Python dependencies
#############################################

WORKDIR /opt/retailflow-build

COPY pyproject.toml uv.lock ./

RUN uv sync \
      --frozen \
      --no-cache \
      --python python3.13 && \
    chown -R spark:spark /opt/.spark-venv


ENV PYSPARK_PYTHON=/opt/.spark-venv/bin/python3.13
ENV PYSPARK_DRIVER_PYTHON=/opt/.spark-venv/bin/python3.13


#############################################
# Spark runtime dirs
#############################################

RUN mkdir -p /tmp/spark-home/.ivy2 && \
    chown -R spark:spark /tmp/spark-home


#############################################
# Copy Spark dependencies
#############################################

COPY --from=spark-deps /spark-jars/*.jar /opt/spark/jars/

ENV SPARK_EXTRA_CLASSPATH=/opt/spark/jars/*
ENV SPARK_EXECUTOR_EXTRA_CLASSPATH=/opt/spark/jars/*


#############################################
# Application
#############################################

WORKDIR /opt/retailflow

USER spark