name: retailflow

x-spark-image: &spark-image
  image: retailflow-spark:4.2.0
  build:
    context: .
    dockerfile: Dockerfile.spark

x-kafka-common: &kafka-common
  image: apache/kafka:4.3.1
  restart: unless-stopped
  networks:
    - retailflow

x-controller-common: &controller-common
  <<: *kafka-common
  environment: &controller-env
    CLUSTER_ID: xYN3lhaZR8qtJRUalXzIgQ
    KAFKA_PROCESS_ROLES: controller
    KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
    KAFKA_CONTROLLER_QUORUM_VOTERS: >
      1@controller-1:19092,
      2@controller-2:19092,
      3@controller-3:19092
    KAFKA_LISTENERS: CONTROLLER://:19092
    KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT

x-broker-common: &broker-common
  <<: *kafka-common
  environment: &broker-env
    CLUSTER_ID: xYN3lhaZR8qtJRUalXzIgQ
    KAFKA_PROCESS_ROLES: broker
    KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
    KAFKA_CONTROLLER_QUORUM_VOTERS: >
      1@controller-1:19092,
      2@controller-2:19092,
      3@controller-3:19092

    KAFKA_LISTENERS: >
      INTERNAL://:9092,
      EXTERNAL://:29092

    KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: >
      INTERNAL:PLAINTEXT,
      EXTERNAL:PLAINTEXT,
      CONTROLLER:PLAINTEXT

    KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL

    KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
    KAFKA_NUM_PARTITIONS: 2

    KAFKA_DEFAULT_REPLICATION_FACTOR: 2
    KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
    KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 2
    KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

services:

  controller-1:
    <<: *controller-common
    hostname: controller-1
    volumes:
      - controller_data_1:/var/lib/kafka/data
    environment:
      <<: *controller-env
      KAFKA_NODE_ID: 1

  controller-2:
    <<: *controller-common
    hostname: controller-2
    volumes:
      - controller_data_2:/var/lib/kafka/data
    environment:
      <<: *controller-env
      KAFKA_NODE_ID: 2

  controller-3:
    <<: *controller-common
    hostname: controller-3
    volumes:
      - controller_data_3:/var/lib/kafka/data
    environment:
      <<: *controller-env
      KAFKA_NODE_ID: 3

  kafka-1:
    <<: *broker-common
    hostname: kafka-1

    ports:
      - "29092:29092"

    volumes:
      - kafka_data_1:/var/lib/kafka/data

    environment:
      <<: *broker-env
      KAFKA_NODE_ID: 4
      KAFKA_ADVERTISED_LISTENERS: >
        INTERNAL://kafka-1:9092,
        EXTERNAL://localhost:29092

    depends_on:
      - controller-1
      - controller-2
      - controller-3

  kafka-2:
    <<: *broker-common
    hostname: kafka-2

    ports:
      - "29093:29092"

    volumes:
      - kafka_data_2:/var/lib/kafka/data

    environment:
      <<: *broker-env
      KAFKA_NODE_ID: 5
      KAFKA_ADVERTISED_LISTENERS: >
        INTERNAL://kafka-2:9092,
        EXTERNAL://localhost:29093

    depends_on:
      - controller-1
      - controller-2
      - controller-3

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:v0.7.2
    ports:
      - 8081:8080
    environment:
      KAFKA_CLUSTERS_0_NAME: docker-local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka-1:9092,kafka-2:9092

      KAFKA_CLUSTERS_0_SCHEMAREGISTRY: http://schema-registry:8081

    depends_on:
      - kafka-1
      - kafka-2

    networks:
      - retailflow

  schema-registry:
    image: confluentinc/cp-schema-registry:8.1.3
    hostname: schema-registry
    container_name: schema-registry
    depends_on:
      - kafka-1
      - kafka-2
    ports:
      - 8082:8081
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081

      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: kafka-1:9092,kafka-2:9092
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:8081/subjects"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5
    networks:
      - retailflow

  alpha-db:
    image: postgres:17.5-alpine3.22
    container_name: alpha-postgres-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=alpha
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=alpha_db
    volumes:
      - alpha_pg_data:/var/lib/postgresql/data
    networks:
      - retailflow

  mongo-db:
    image: mongo:8.2.11
    container_name: mongo-db
    ports:
      - 27017:27017
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - retailflow

  mongo-express:
    image: mongo-express:1.0.2-20-alpine3.19
    restart: always
    ports:
      - 8083:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo-db:27017/
      ME_CONFIG_BASICAUTH_ENABLED: true
      ME_CONFIG_BASICAUTH_USERNAME: mongoexpressuser
      ME_CONFIG_BASICAUTH_PASSWORD: mongoexpresspass
    networks:
      - retailflow

  storage:
    image: quay.io/minio/aistor/minio:RELEASE.2026-03-26T21-24-40Z
    command: minio server /mnt/data --license /minio.license
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/mnt/data
      - ./minio/minio.license:/minio.license
      - ./minio/certs:/etc/minio/certs
    environment:
      MINIO_ROOT_USER: ${S3_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${S3_SECRET_KEY}
      MINIO_NOTIFY_KAFKA_ENABLE_LANDING_EVENTS: on
      MINIO_NOTIFY_KAFKA_BROKERS_LANDING_EVENTS: kafka-1:9092,kafka-2:9092
      MINIO_NOTIFY_KAFKA_TOPIC_LANDING_EVENTS: ${MINIO_NOTIFY_KAFKA_TOPIC_LANDING_EVENTS}
    networks:
      - retailflow
    depends_on:
      - kafka-1
      - kafka-2

# spark

  spark-master:
    <<: *spark-image
    container_name: spark-master
    ports:
      - 8084:8080   # Web UI
      - 7077:7077   # Spark master
    # volumes:
    #   - ./:/opt/retailflow
    command: >
      /opt/spark/bin/spark-class
      org.apache.spark.deploy.master.Master
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - retailflow

  spark-worker-1:
    <<: *spark-image
    container_name: spark-worker-1
    # volumes:
    #   - ./:/opt/retailflow
    environment:
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 4g
    command: >
      /opt/spark/bin/spark-class
      org.apache.spark.deploy.worker.Worker
      --cores 2
      --memory 4g
      spark://spark-master:7077
    depends_on:
      spark-master:
        condition: service_healthy
    networks:
      - retailflow

  spark-worker-2:
    <<: *spark-image
    container_name: spark-worker-2
    # volumes:
    #   - ./:/opt/retailflow
    environment:
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 4g
    command: >
      /opt/spark/bin/spark-class
      org.apache.spark.deploy.worker.Worker
      --cores 2
      --memory 4g
      spark://spark-master:7077
    depends_on:
      spark-master:
        condition: service_healthy
    networks:
      - retailflow


  spark-submit:
    <<: *spark-image
    container_name: spark-submit
    volumes:
      - ./:/opt/retailflow
    command: tail -f /dev/null
    environment:
      HOME: /tmp/spark-home
    depends_on:
      spark-master:
        condition: service_healthy
    networks:
      - retailflow

volumes:
  controller_data_1:
  controller_data_2:
  controller_data_3:

  kafka_data_1:
  kafka_data_2:
  alpha_pg_data:
  minio_data:

networks:
  retailflow:
    external: true
    name: retailflow